import { describe, expect, it, beforeEach } from "vitest";
import { GetPostTagByIdUseCase } from "./get-post-tag-by-id.use-case";
import { PostTagRepository } from "@/infra/repositories/test";
import { PostTag } from "@/domain/post-tag";
import { ResourceNotFoundException } from "@caffeine/errors/application";

describe("GetPostTagByIdUseCase", () => {
	let repository: PostTagRepository;
	let useCase: GetPostTagByIdUseCase;

	beforeEach(() => {
		repository = new PostTagRepository();
		useCase = new GetPostTagByIdUseCase(repository);
	});

	describe("run", () => {
		it("should find and return a post tag by id", async () => {
			const tag = PostTag.make({
				name: "Test Tag",
				slug: "test-tag",
				hidden: false,
			});
			await repository.create(tag);

			const result = await useCase.run(tag.id);

			expect(result).toBeDefined();
			expect(result.id).toBe(tag.id);
			expect(result.name).toBe("Test Tag");
			expect(result.slug).toBe("test-tag");
			expect(result.hidden).toBe(false);
		});

		it("should throw ResourceNotFoundException when tag does not exist", async () => {
			await expect(useCase.run("non-existent-id")).rejects.toThrow(
				ResourceNotFoundException,
			);
		});

		it("should find hidden tags", async () => {
			const tag = PostTag.make({
				name: "Hidden Tag",
				slug: "hidden-tag",
				hidden: true,
			});
			await repository.create(tag);

			const result = await useCase.run(tag.id);

			expect(result.hidden).toBe(true);
		});

		it("should return the correct tag among multiple tags", async () => {
			const tag1 = PostTag.make({
				name: "Tag 1",
				slug: "tag-1",
				hidden: false,
			});
			const tag2 = PostTag.make({
				name: "Tag 2",
				slug: "tag-2",
				hidden: false,
			});
			const tag3 = PostTag.make({
				name: "Tag 3",
				slug: "tag-3",
				hidden: false,
			});

			await repository.create(tag1);
			await repository.create(tag2);
			await repository.create(tag3);

			const result = await useCase.run(tag2.id);

			expect(result.id).toBe(tag2.id);
			expect(result.name).toBe("Tag 2");
			expect(result.slug).toBe("tag-2");
		});

		it("should return all properties of the unmounted tag", async () => {
			const tag = PostTag.make({
				name: "Complete Tag",
				slug: "complete-tag",
				hidden: false,
			});
			await repository.create(tag);

			const result = await useCase.run(tag.id);

			expect(result).toHaveProperty("id");
			expect(result).toHaveProperty("name");
			expect(result).toHaveProperty("slug");
			expect(result).toHaveProperty("hidden");
			expect(result).toHaveProperty("createdAt");
			expect(result).toHaveProperty("updatedAt");
		});

		it("should throw ResourceNotFoundException with descriptive message", async () => {
			const fakeId = "fake-id-12345";
			try {
				await useCase.run(fakeId);
				expect.fail("Should have thrown ResourceNotFoundException");
			} catch (error) {
				expect(error).toBeInstanceOf(ResourceNotFoundException);
				if (error instanceof ResourceNotFoundException) {
					expect(error.message).toContain(fakeId);
				}
			}
		});

		it("should not find tag by slug instead of id", async () => {
			const tag = PostTag.make({
				name: "Test Tag",
				slug: "test-tag",
				hidden: false,
			});
			await repository.create(tag);

			// Trying to find by slug should fail since it expects an id
			await expect(useCase.run("test-tag")).rejects.toThrow(
				ResourceNotFoundException,
			);
		});

		it("should handle uuid format ids", async () => {
			const tag = PostTag.make({
				name: "UUID Tag",
				slug: "uuid-tag",
				hidden: false,
			});
			await repository.create(tag);

			// The id is a uuid generated by PostTag.make
			const result = await useCase.run(tag.id);

			expect(result.id).toBe(tag.id);
			expect(result.id).toMatch(
				/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i,
			);
		});

		it("should find tag with different hidden states", async () => {
			const visibleTag = PostTag.make({
				name: "Visible Tag",
				slug: "visible-tag",
				hidden: false,
			});
			const hiddenTag = PostTag.make({
				name: "Hidden Tag 2",
				slug: "hidden-tag-2",
				hidden: true,
			});

			await repository.create(visibleTag);
			await repository.create(hiddenTag);

			const visibleResult = await useCase.run(visibleTag.id);
			const hiddenResult = await useCase.run(hiddenTag.id);

			expect(visibleResult.hidden).toBe(false);
			expect(hiddenResult.hidden).toBe(true);
		});

		it("should return matching id in result", async () => {
			const tag = PostTag.make({
				name: "ID Match Tag",
				slug: "id-match-tag",
				hidden: false,
			});
			await repository.create(tag);

			const result = await useCase.run(tag.id);

			expect(result.id).toBe(tag.id);
		});
	});
});
